### ISSUE TITLE
Importing feeds lasts for more than 24 hours

### ISSUE THREAD

**Issue by ddeimeke** [onli/feedtragon#17]
Please speed up the feed import.

I started the import of 622 feeds yesterday morning and today I see that "only" 550 feeds are done.

**Comment by onli** [comment]
Done yesterday in https://github.com/onli/feedtragon/commit/7484634f9987eb3695299ed3f6f5130fb89398c1, think that landed on the server the evening :)

There was something wrong in the slow version that made it run for forever, repeating itself. But that did not happen on my development machine. I hope it won't happen with the new strategy.

Please try importing the feeds again. It should be done in ~5 minutes, faster since he only needs to speak to superfeedr for the remaining 72 feeds.

**Comment by onli** [comment]
I'll close here for now as you signaled it works now for you.
